[general]
connection = "Server=server;Database=db_38f4f774_6a12_4f37_a869_ea52ccde464f;TrustServerCertificate=True"
output = "Schema.fs"
namespace = "SqlHydraForSqlite"
cli_mutable = true
[sqlhydra_query_integration]
provider_db_type_attributes = true
[readers]
reader_type = "System.Data.Common.DbDataReader"
[filters]
include = []
exclude = []
