[general]
connection = "Server=server;Database=db_781c8430_468a_421d_a0d5_106096079d69;TrustServerCertificate=True"
output = "Schema.fs"
namespace = "SqlHydraForSqlite"
cli_mutable = true
[sqlhydra_query_integration]
provider_db_type_attributes = true
[readers]
reader_type = "System.Data.Common.DbDataReader"
[filters]
include = []
exclude = []
